import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  ShieldAlert, Landmark, AlertTriangle, Users, CheckCircle, MapPin, X, ArrowRight, 
  Map, Search, Download, Radio, Megaphone, Activity, TrendingUp, BarChart2, PieChart as PieChartIcon, 
  List, Phone, Shield, FileText, LogOut, Clock, Target, Flag, Send, ChevronRight, FileDown, Plus, Filter, LayoutDashboard,
  ChevronDown, ChevronUp
} from 'lucide-react';

import StatCard from '../../shared/components/StatCard';
import api from '../../services/api';
import tnConstituencies from '../../data/tn_constituencies.json';

export default function CmDashboard() {
  const { t, i18n } = useTranslation();
  const navigate = useNavigate();
  const isTa = i18n.language === 'ta';
  const tLabel = (en, ta) => isTa ? ta : en;

  // State
  const [activeMenu, setActiveMenu] = useState('dashboard');
  const [tickets, setTickets] = useState([]);
  
  // Drill-down State (Macro Dashboard)
  const [selectedDistrict, setSelectedDistrict] = useState(null);
  const [selectedDepartment, setSelectedDepartment] = useState(null);

  // Constituency Grid State
  const [constituencyFilterDistrict, setConstituencyFilterDistrict] = useState('All Districts');
  const [constituencySearch, setConstituencySearch] = useState('');
  const [constituencySort, setConstituencySort] = useState({ column: 'pending', direction: 'desc' });
  const [expandedConstituency, setExpandedConstituency] = useState(null);

  // Broadcast announcements state
  const [announcements, setAnnouncements] = useState(() => JSON.parse(localStorage.getItem('jn_cm_announcements') || '[]'));
  const [broadcastTitle, setBroadcastTitle] = useState('');
  const [broadcastText, setBroadcastText] = useState('');
  const [broadcastDistrict, setBroadcastDistrict] = useState('All');

  // Cabinet Report Generation state
  const [cabinetReport, setCabinetReport] = useState(null);

  // Fetch all tickets
  const fetchTickets = async () => {
    try {
      const res = await api.get('/tickets');
      let formatted = res.data.map(t => {
        const districtName = t.jurisdiction?.name || 'Unknown';
        
        // Deterministic mock mapping of tickets to a constituency within their district
        // In real world, t.constituency would be provided.
        let assignedConstituency = null;
        const districtConsts = tnConstituencies.filter(c => c.district === districtName);
        if (districtConsts.length > 0) {
           const hash = t.id ? t.id.toString().charCodeAt(0) + t.id.toString().charCodeAt(t.id.toString().length - 1) : 0;
           assignedConstituency = districtConsts[hash % districtConsts.length].constituency;
        }

        return {
          ...t,
          category: t.categoryName || t.department?.name || 'Unknown',
          district: districtName,
          assignedConstituency: assignedConstituency,
          displayId: t.ticketNumber,
          id: t.id,
          description: t.description,
          ward: t.jurisdiction?.name || 'Unknown'
        };
      });

      // --- INJECT MASSIVE DUMMY DATA FOR DEMONSTRATION PURPOSES ---
      const dummyDepartments = ['Electricity', 'Health & Sanitation', 'Water (TWAD)', 'PWD / Roads', 'Revenue', 'Police', 'Transport'];
      const statuses = ['SUBMITTED', 'ASSIGNED', 'IN_PROGRESS', 'ESCALATED', 'RESOLVED', 'CLOSED'];
      
      const massiveDummy = [];
      // Generate random ticket volume per constituency
      tnConstituencies.forEach(c => {
        const count = Math.floor(Math.random() * 60) + 10; // 10 to 70 tickets per constituency
        for(let i = 0; i < count; i++) {
          const status = statuses[Math.floor(Math.random() * statuses.length)];
          const dept = dummyDepartments[Math.floor(Math.random() * dummyDepartments.length)];
          // create random dates within last 30 days
          const created = new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000);
          const updated = new Date(created.getTime() + Math.random() * 5 * 24 * 60 * 60 * 1000);
          
          massiveDummy.push({
            id: `dummy-${c.no}-${i}`,
            ticketNumber: `DUMMY-${c.no}-${i}`,
            displayId: `DUMMY-${c.no}-${i}`,
            category: dept,
            district: c.district,
            assignedConstituency: c.constituency,
            status: status,
            createdAt: created.toISOString(),
            updatedAt: updated.toISOString(),
            description: 'Autogenerated dummy ticket for macro view'
          });
        }
      });
      
      formatted = [...formatted, ...massiveDummy];
      // -----------------------------------------------------------

      setTickets(formatted);
    } catch (err) {
      console.error('Failed to fetch CM tickets:', err);
    }
  };

  useEffect(() => {
    fetchTickets();
  }, []);

  const handleLogout = () => {
    localStorage.removeItem('jn_emp_role');
    localStorage.removeItem('jn_emp_dept');
    localStorage.removeItem('jn_emp_jurisdiction');
    localStorage.removeItem('jn_emp_constituency');
    localStorage.removeItem('jn_emp_district');
    localStorage.removeItem('jn_lang');
    navigate('/');
  };

  // Cabinet Report Generation ranking ministers
  const handleGenerateCabinetReport = () => {
    const reportDate = new Date().toLocaleDateString();
    
    const deptsList = [...new Set(tickets.map(t => t.category))].filter(Boolean);
    const rankings = deptsList.map(dept => {
      const deptTickets = tickets.filter(t => t.category === dept);
      const resolved = deptTickets.filter(t => t.status === 'RESOLVED' || t.status === 'CLOSED').length;
      const rate = deptTickets.length > 0 ? Math.round((resolved / deptTickets.length) * 100) : 100;
      
      let minister = 'Cabinet Minister';
      if (dept === 'Electricity') minister = 'C. T. R. Nirmal Kumar';
      if (dept === 'Health & Sanitation' || dept === 'Sanitation') minister = 'Dr. K.G. Arunraj';
      if (dept.includes('Water')) minister = 'Sec. Hariharan';
      if (dept.includes('PWD') || dept.includes('Roads')) minister = 'CE Karthikeyan';

      return { dept, minister, rate, pending: deptTickets.length - resolved };
    }).sort((a, b) => b.rate - a.rate);

    const report = {
      title: 'TAMIL NADU STATE CABINET EFFICIENCY SUMMARY',
      date: reportDate,
      rankings,
      summaryText: 'Aggregate departmental performance audit completed based on civic grievance resolutions.'
    };
    setCabinetReport(report);
  };

  // Propose Broadcast Announcement
  const handleBroadcast = (e) => {
    e.preventDefault();
    if (!broadcastTitle.trim() || !broadcastText.trim()) return;

    const newBroadcast = {
      id: Date.now().toString(),
      title: broadcastTitle,
      text: broadcastText,
      district: broadcastDistrict,
      date: new Date().toLocaleString()
    };

    const updated = [newBroadcast, ...announcements];
    setAnnouncements(updated);
    localStorage.setItem('jn_cm_announcements', JSON.stringify(updated));
    setBroadcastTitle('');
    setBroadcastText('');
    alert('Statewide CM Announcement broadcasted successfully!');
  };

  const renderSidebar = () => {
    const menuItems = [
      { id: 'dashboard', label: tLabel('State Command', 'மாநில கட்டளை'), icon: <LayoutDashboard /> },
      { id: 'constituencies', label: tLabel('Grievances', 'குறைகள்'), icon: <Map /> },
      { id: 'cabinet', label: tLabel('Cabinet Rankings', 'அமைச்சரவை தரவரிசை'), icon: <Landmark /> },
      { id: 'broadcast', label: tLabel('CM Announcements', 'அரசு அறிவிப்புகள்'), icon: <Megaphone /> },
    ];

    return (
      <aside className="hidden md:flex w-[240px] bg-[#1E1E1E] text-slate-200 border-r border-slate-800 flex-col justify-between shrink-0 select-none h-full shadow-2xl">
        <div>
          <div className="p-5 border-b border-slate-800 flex items-center gap-2">
            <Shield className="w-6 h-6 text-[#FF3B30]" />
            <div>
              <h1 className="text-sm font-black text-[#FF3B30] tracking-wider uppercase leading-none">JanaNayagam</h1>
              <span className="text-[9px] font-bold text-slate-500 uppercase tracking-widest mt-1 block">CHIEF MINISTER</span>
            </div>
          </div>
          <nav className="p-4 space-y-1.5">
            {menuItems.map(item => (
              <button
                key={item.id}
                onClick={() => setActiveMenu(item.id)}
                className={`w-full flex items-center text-left gap-3 px-4 py-3 rounded-xl text-xs font-black uppercase tracking-wider transition-all duration-200 ${
                  activeMenu === item.id ? 'bg-[#FF3B30]/15 text-[#FF3B30] border-l-4 border-[#FF3B30]' : 'text-slate-400 hover:bg-slate-900 hover:text-white'
                }`}
              >
                {React.cloneElement(item.icon, { className: 'w-4 h-4 shrink-0' })}
                <span>{item.label}</span>
              </button>
            ))}
          </nav>
        </div>
        <div className="p-4 border-t border-slate-800 space-y-3">
          <div className="flex items-center gap-2.5 p-2 bg-slate-900/50 rounded-xl border border-slate-800/40">
            <div className="w-8 h-8 rounded-full bg-[#FF3B30] text-white flex items-center justify-center font-black text-xs shadow-inner">
              CJ
            </div>
            <div className="flex flex-col overflow-hidden">
              <span className="text-xs font-black text-slate-100 truncate">Hon. Chief Minister</span>
              <span className="text-[8px] text-slate-500 font-extrabold uppercase">STATE OF TAMIL NADU</span>
            </div>
          </div>
          <button onClick={handleLogout} className="w-full flex items-center justify-center gap-1.5 py-2.5 rounded-xl bg-red-950/20 text-[10px] font-black text-red-400 uppercase border border-red-900/30 hover:bg-red-900/40 transition-colors">
            <LogOut className="w-3.5 h-3.5" /> <span>Logout</span>
          </button>
        </div>
      </aside>
    );
  };

  // --------------------------------------------------------
  // MACRO DASHBOARD LOGIC 
  // --------------------------------------------------------
  const renderDashboard = () => {
    const filteredTickets = tickets.filter(t => {
      if (selectedDistrict && t.district !== selectedDistrict) return false;
      if (selectedDepartment && t.category !== selectedDepartment) return false;
      return true;
    });

    const totalTickets = filteredTickets.length;
    const totalResolved = filteredTickets.filter(t => t.status === 'RESOLVED' || t.status === 'CLOSED').length;
    const resolutionRate = totalTickets > 0 ? Math.round((totalResolved / totalTickets) * 100) : 100;
    const totalPending = totalTickets - totalResolved;

    const resolvedTickets = filteredTickets.filter(t => t.status === 'RESOLVED' || t.status === 'CLOSED');
    let avgResTime = "48 hrs";
    if (resolvedTickets.length > 0) {
      let totalMs = 0;
      let validCount = 0;
      resolvedTickets.forEach(t => {
        if (t.createdAt && t.updatedAt) {
          totalMs += (new Date(t.updatedAt) - new Date(t.createdAt));
          validCount++;
        }
      });
      if (validCount > 0) {
        const avgHours = Math.round((totalMs / validCount) / (1000 * 60 * 60));
        avgResTime = `${avgHours} hrs`;
      } else {
        avgResTime = `${Math.max(24, Math.round(totalPending * 0.5))} hrs`;
      }
    }

    const SEVEN_DAYS_MS = 7 * 24 * 60 * 60 * 1000;
    const now = new Date();
    let agingTicketsCount = 0;
    filteredTickets.forEach(t => {
      if (t.status === 'RESOLVED' || t.status === 'CLOSED') return;
      if (t.createdAt) {
        if ((now - new Date(t.createdAt)) > SEVEN_DAYS_MS) agingTicketsCount++;
      } else {
        if (Math.random() > 0.8) agingTicketsCount++;
      }
    });

    const allDistricts = [...new Set(tickets.map(t => t.district))].filter(Boolean);
    const districtRanking = allDistricts.map(d => {
      const dTickets = tickets.filter(t => t.district === d && (!selectedDepartment || t.category === selectedDepartment));
      const pending = dTickets.filter(t => t.status !== 'RESOLVED' && t.status !== 'CLOSED').length;
      const total = dTickets.length;
      const rate = total > 0 ? Math.round(((total - pending) / total) * 100) : 100;
      return { name: d, pending, rate, total };
    }).filter(d => d.total > 0).sort((a, b) => b.pending - a.pending);

    const allDepartments = [...new Set(tickets.map(t => t.category))].filter(Boolean);
    const heatmapDistricts = selectedDistrict ? [selectedDistrict] : allDistricts;
    const heatmapDepartments = selectedDepartment ? [selectedDepartment] : allDepartments;

    const getHeatmapColor = (pendingCount, maxPending) => {
      if (pendingCount === 0) return 'bg-slate-50 text-slate-400';
      const intensity = Math.min(1, pendingCount / (maxPending || 1));
      if (intensity < 0.2) return 'bg-orange-100 text-orange-800';
      if (intensity < 0.5) return 'bg-orange-300 text-orange-900';
      if (intensity < 0.8) return 'bg-red-400 text-white';
      return 'bg-red-600 text-white font-bold';
    };

    let maxHeatmapPending = 1;
    const heatmapData = heatmapDepartments.map(dept => {
      const row = { department: dept, districts: {} };
      heatmapDistricts.forEach(dist => {
        const pending = tickets.filter(t => t.category === dept && t.district === dist && t.status !== 'RESOLVED' && t.status !== 'CLOSED').length;
        if (pending > maxHeatmapPending) maxHeatmapPending = pending;
        row.districts[dist] = pending;
      });
      return row;
    });

    return (
      <div className="space-y-6">
        {/* DRILL DOWN BREADCRUMBS */}
        <div className="bg-white rounded-xl p-4 shadow-sm border border-slate-200 flex items-center gap-2 text-xs font-black uppercase tracking-wide">
          <Filter className="w-4 h-4 text-[#FF3B30]" />
          <span className="text-slate-400 ml-2">Scope:</span>
          <button 
            onClick={() => { setSelectedDepartment(null); setSelectedDistrict(null); }}
            className={`hover:text-[#FF3B30] transition-colors ${!selectedDepartment && !selectedDistrict ? 'text-[#FF3B30]' : 'text-slate-700'}`}
          >
            Statewide
          </button>
          
          {selectedDepartment && (
            <>
              <ChevronRight className="w-4 h-4 text-slate-300" />
              <button 
                onClick={() => setSelectedDistrict(null)}
                className="text-[#FF3B30] flex items-center gap-1 hover:opacity-80"
              >
                Dept: {selectedDepartment} <X className="w-3 h-3 ml-1" onClick={(e) => { e.stopPropagation(); setSelectedDepartment(null); }} />
              </button>
            </>
          )}

          {selectedDistrict && (
            <>
              <ChevronRight className="w-4 h-4 text-slate-300" />
              <button 
                className="text-[#FF3B30] flex items-center gap-1 hover:opacity-80"
              >
                Dist: {selectedDistrict} <X className="w-3 h-3 ml-1" onClick={() => setSelectedDistrict(null)} />
              </button>
            </>
          )}
        </div>

        {/* STATE-WIDE KPI SUMMARY CARDS */}
        <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
          <StatCard label="Total Grievances" value={totalTickets} icon={<List className="text-blue-500 w-5 h-5" />} color="blue" />
          <StatCard label="Resolution Rate" value={`${resolutionRate}%`} icon={<CheckCircle className="text-emerald-500 w-5 h-5" />} color="green" />
          <StatCard label="Avg. Resolution Time" value={avgResTime} icon={<Clock className="text-indigo-500 w-5 h-5" />} color="indigo" />
          <StatCard label="Total Pending" value={totalPending} icon={<Activity className="text-amber-500 w-5 h-5" />} color="orange" />
          <StatCard label="Aging (Longest Unresolved)" value={agingTicketsCount} icon={<AlertTriangle className="text-rose-500 w-5 h-5" />} color="red" />
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-1 gap-6">
          {/* DISTRICT RANKING */}
          <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-200/80">
            <div className="flex justify-between items-center mb-4 border-b border-slate-100 pb-3">
              <div>
                <h3 className="font-black text-slate-800 text-sm uppercase tracking-wide">
                  Unresolved Load Ranking
                </h3>
                <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest block mt-0.5">
                  Districts sorted by highest pending volume
                </span>
              </div>
              <TrendingUp className="w-5 h-5 text-[#FF3B30]" />
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-8 gap-y-3 overflow-y-auto max-h-[250px] pr-2 custom-scrollbar">
              {districtRanking.map((d, index) => (
                <div 
                  key={d.name} 
                  className="group cursor-pointer p-2 hover:bg-slate-50 rounded-lg transition-colors border border-transparent hover:border-slate-200"
                  onClick={() => setSelectedDistrict(d.name)}
                >
                  <div className="flex justify-between font-bold text-slate-700 uppercase text-[10px] mb-1.5">
                    <span className="font-black flex items-center gap-2">
                      <span className="w-4 h-4 rounded-full bg-slate-200 text-slate-500 flex items-center justify-center text-[8px] group-hover:bg-[#FF3B30] group-hover:text-white transition-colors">{index + 1}</span> 
                      {d.name}
                    </span>
                    <span className={d.pending > 0 ? 'text-[#FF3B30]' : 'text-slate-500'}>
                      {d.pending} Pending <span className="text-slate-400 mx-1">|</span> {d.rate}% Res
                    </span>
                  </div>
                  <div className="h-2 w-full bg-slate-100 rounded-full overflow-hidden flex">
                    <div className="h-full bg-emerald-500" style={{ width: `${d.rate}%` }}></div>
                    <div className="h-full bg-red-500" style={{ width: `${100 - d.rate}%` }}></div>
                  </div>
                </div>
              ))}
              {districtRanking.length === 0 && (
                <div className="text-xs text-slate-500 font-bold col-span-2 text-center py-4">No data available for the current selection.</div>
              )}
            </div>
          </div>

          {/* DEPARTMENT-WISE PENDING HEATMAP */}
          <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-200/80 overflow-hidden flex flex-col">
            <div className="flex justify-between items-center mb-4 border-b border-slate-100 pb-3 shrink-0">
              <div>
                <h3 className="font-black text-slate-800 text-sm uppercase tracking-wide">
                  Pending Intensity Heatmap
                </h3>
                <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest block mt-0.5">
                  Department vs District Backlog
                </span>
              </div>
              <div className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-widest text-slate-400">
                <span>Low</span>
                <div className="flex gap-0.5">
                  <span className="w-3 h-3 bg-slate-50 border border-slate-200"></span>
                  <span className="w-3 h-3 bg-orange-100"></span>
                  <span className="w-3 h-3 bg-orange-300"></span>
                  <span className="w-3 h-3 bg-red-400"></span>
                  <span className="w-3 h-3 bg-red-600"></span>
                </div>
                <span>High</span>
              </div>
            </div>
            
            <div className="overflow-x-auto custom-scrollbar pb-4 flex-1">
              <table className="w-full text-left border-collapse min-w-max">
                <thead>
                  <tr>
                    <th className="p-3 sticky left-0 z-10 bg-white border-b border-slate-200 shadow-[2px_0_5px_rgba(0,0,0,0.05)] text-[10px] font-black text-slate-500 uppercase">Department</th>
                    {heatmapDistricts.map(dist => (
                      <th 
                        key={dist} 
                        onClick={() => setSelectedDistrict(dist === selectedDistrict ? null : dist)}
                        className="p-3 border-b border-slate-200 text-[9px] font-black text-slate-500 uppercase text-center cursor-pointer hover:text-[#FF3B30] transition-colors"
                      >
                        <div className="w-20 truncate mx-auto" title={dist}>{dist}</div>
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {heatmapData.map(row => (
                    <tr key={row.department} className="hover:bg-slate-50">
                      <td 
                        className="p-3 sticky left-0 z-10 bg-white shadow-[2px_0_5px_rgba(0,0,0,0.02)] border-b border-slate-100 text-[10px] font-black text-slate-700 uppercase cursor-pointer hover:text-[#FF3B30] transition-colors"
                        onClick={() => setSelectedDepartment(row.department === selectedDepartment ? null : row.department)}
                      >
                        <div className="flex items-center gap-2 w-40 truncate" title={row.department}>
                          {row.department}
                        </div>
                      </td>
                      {heatmapDistricts.map(dist => {
                        const count = row.districts[dist];
                        return (
                          <td key={dist} className="p-1 border-b border-slate-50">
                            <div 
                              className={`w-full h-8 flex items-center justify-center rounded-md text-[10px] transition-all cursor-pointer hover:ring-2 hover:ring-[#FF3B30] hover:ring-offset-1 ${getHeatmapColor(count, maxHeatmapPending)}`}
                              title={`${row.department} in ${dist}: ${count} Pending`}
                              onClick={() => {
                                setSelectedDepartment(row.department);
                                setSelectedDistrict(dist);
                              }}
                            >
                              {count > 0 ? count : '-'}
                            </div>
                          </td>
                        );
                      })}
                    </tr>
                  ))}
                  {heatmapData.length === 0 && (
                    <tr>
                      <td colSpan={heatmapDistricts.length + 1} className="p-4 text-center text-xs font-bold text-slate-500">
                        No data available
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    );
  };

  // --------------------------------------------------------
  // CONSTITUENCIES TAB LOGIC
  // --------------------------------------------------------
  const renderConstituenciesTab = () => {
    // 1. Data mapping
    const constData = tnConstituencies.map(c => {
      const cTickets = tickets.filter(t => t.assignedConstituency === c.constituency);
      const total = cTickets.length;
      const resolved = cTickets.filter(t => t.status === 'RESOLVED' || t.status === 'CLOSED').length;
      const pending = total - resolved;
      const rate = total > 0 ? Math.round((resolved / total) * 100) : 0;
      return { ...c, total, pending, resolved, rate, tickets: cTickets };
    });

    // 2. Filter
    let filteredData = constData;
    if (constituencyFilterDistrict !== 'All Districts') {
      filteredData = filteredData.filter(c => c.district === constituencyFilterDistrict);
    }
    if (constituencySearch.trim()) {
      const s = constituencySearch.toLowerCase();
      filteredData = filteredData.filter(c => 
        c.constituency.toLowerCase().includes(s) || c.district.toLowerCase().includes(s)
      );
    }

    // 3. Sort
    filteredData.sort((a, b) => {
      let valA = a[constituencySort.column];
      let valB = b[constituencySort.column];
      if (constituencySort.column === 'no') {
        valA = a.no; valB = b.no;
      }
      if (valA < valB) return constituencySort.direction === 'asc' ? -1 : 1;
      if (valA > valB) return constituencySort.direction === 'asc' ? 1 : -1;
      return 0;
    });

    // Handle sort click
    const handleSort = (col) => {
      if (constituencySort.column === col) {
        setConstituencySort({ column: col, direction: constituencySort.direction === 'asc' ? 'desc' : 'asc' });
      } else {
        setConstituencySort({ column: col, direction: 'desc' }); // default to desc for numeric metrics
      }
    };

    const districtList = ['All Districts', ...new Set(tnConstituencies.map(c => c.district))].sort();

    // District Summary calculations if one is selected
    let distSummary = null;
    if (constituencyFilterDistrict !== 'All Districts') {
      const dTotal = filteredData.reduce((acc, c) => acc + c.total, 0);
      const dResolved = filteredData.reduce((acc, c) => acc + c.resolved, 0);
      const dPending = filteredData.reduce((acc, c) => acc + c.pending, 0);
      const dRate = dTotal > 0 ? Math.round((dResolved / dTotal) * 100) : 0;
      distSummary = { total: dTotal, resolved: dResolved, pending: dPending, rate: dRate };
    }

    return (
      <div className="space-y-6">
        <div className="flex flex-col md:flex-row gap-4 items-end justify-between bg-white p-4 rounded-2xl shadow-sm border border-slate-200/80">
          <div className="flex flex-col gap-1.5 flex-1 w-full max-w-xs">
            <label className="text-[10px] font-bold text-slate-500 uppercase tracking-widest pl-1">District Filter</label>
            <div className="relative">
              <MapPin className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
              <select 
                value={constituencyFilterDistrict}
                onChange={e => setConstituencyFilterDistrict(e.target.value)}
                className="w-full bg-slate-50 border border-slate-200 text-xs font-bold rounded-xl p-2.5 pl-9 outline-none cursor-pointer focus:border-[#FF3B30] transition-colors"
              >
                {districtList.map(d => (
                  <option key={d} value={d}>{d}</option>
                ))}
              </select>
            </div>
          </div>
          
          <div className="flex flex-col gap-1.5 flex-1 w-full max-w-xs">
            <label className="text-[10px] font-bold text-slate-500 uppercase tracking-widest pl-1">Search Matrix</label>
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
              <input 
                type="text" 
                placeholder="Constituency or District..."
                value={constituencySearch}
                onChange={e => setConstituencySearch(e.target.value)}
                className="w-full bg-slate-50 border border-slate-200 text-xs font-bold rounded-xl p-2.5 pl-9 outline-none focus:border-[#FF3B30] transition-colors"
              />
            </div>
          </div>
        </div>

        {distSummary && (
          <motion.div initial={{ opacity: 0, y: 5 }} animate={{ opacity: 1, y: 0 }} className="grid grid-cols-4 gap-4">
            <div className="bg-blue-50 border border-blue-200 p-4 rounded-2xl text-center">
              <div className="text-[10px] font-bold text-blue-600 uppercase tracking-widest mb-1">Total</div>
              <div className="text-xl font-black text-blue-900">{distSummary.total}</div>
            </div>
            <div className="bg-orange-50 border border-orange-200 p-4 rounded-2xl text-center">
              <div className="text-[10px] font-bold text-orange-600 uppercase tracking-widest mb-1">Pending</div>
              <div className="text-xl font-black text-orange-900">{distSummary.pending}</div>
            </div>
            <div className="bg-emerald-50 border border-emerald-200 p-4 rounded-2xl text-center">
              <div className="text-[10px] font-bold text-emerald-600 uppercase tracking-widest mb-1">Resolved</div>
              <div className="text-xl font-black text-emerald-900">{distSummary.resolved}</div>
            </div>
            <div className="bg-indigo-50 border border-indigo-200 p-4 rounded-2xl text-center">
              <div className="text-[10px] font-bold text-indigo-600 uppercase tracking-widest mb-1">Resolution Rate</div>
              <div className="text-xl font-black text-indigo-900">{distSummary.rate}%</div>
            </div>
          </motion.div>
        )}

        <div className="bg-white rounded-3xl shadow-sm border border-slate-200/80 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200">
                  <th onClick={() => handleSort('no')} className="p-4 text-[10px] font-black text-slate-500 uppercase cursor-pointer hover:text-slate-800 w-16">
                    AC No {constituencySort.column === 'no' && (constituencySort.direction === 'asc' ? '↑' : '↓')}
                  </th>
                  <th onClick={() => handleSort('constituency')} className="p-4 text-[10px] font-black text-slate-500 uppercase cursor-pointer hover:text-slate-800">
                    Constituency {constituencySort.column === 'constituency' && (constituencySort.direction === 'asc' ? '↑' : '↓')}
                  </th>
                  <th onClick={() => handleSort('district')} className="p-4 text-[10px] font-black text-slate-500 uppercase cursor-pointer hover:text-slate-800">
                    District {constituencySort.column === 'district' && (constituencySort.direction === 'asc' ? '↑' : '↓')}
                  </th>
                  <th onClick={() => handleSort('total')} className="p-4 text-[10px] font-black text-slate-500 uppercase cursor-pointer hover:text-slate-800 text-right">
                    Total {constituencySort.column === 'total' && (constituencySort.direction === 'asc' ? '↑' : '↓')}
                  </th>
                  <th onClick={() => handleSort('pending')} className="p-4 text-[10px] font-black text-orange-500 uppercase cursor-pointer hover:text-orange-700 text-right">
                    Pending {constituencySort.column === 'pending' && (constituencySort.direction === 'asc' ? '↑' : '↓')}
                  </th>
                  <th onClick={() => handleSort('resolved')} className="p-4 text-[10px] font-black text-emerald-600 uppercase cursor-pointer hover:text-emerald-800 text-right">
                    Resolved {constituencySort.column === 'resolved' && (constituencySort.direction === 'asc' ? '↑' : '↓')}
                  </th>
                  <th onClick={() => handleSort('rate')} className="p-4 text-[10px] font-black text-indigo-600 uppercase cursor-pointer hover:text-indigo-800 text-right">
                    Res % {constituencySort.column === 'rate' && (constituencySort.direction === 'asc' ? '↑' : '↓')}
                  </th>
                  <th className="p-4"></th>
                </tr>
              </thead>
              <tbody className="text-xs">
                {filteredData.map(c => {
                  const isExpanded = expandedConstituency === c.no;
                  
                  // Department breakdown calculation
                  let deptBreakdown = [];
                  if (isExpanded) {
                    const depts = [...new Set(c.tickets.map(t => t.category))].filter(Boolean);
                    deptBreakdown = depts.map(dept => {
                      const dTickets = c.tickets.filter(t => t.category === dept);
                      const dRes = dTickets.filter(t => t.status === 'RESOLVED' || t.status === 'CLOSED').length;
                      return {
                        dept,
                        total: dTickets.length,
                        pending: dTickets.length - dRes,
                        resolved: dRes
                      };
                    }).sort((a,b) => b.pending - a.pending);
                  }

                  return (
                    <React.Fragment key={c.no}>
                      <tr 
                        onClick={() => setExpandedConstituency(isExpanded ? null : c.no)}
                        className={`border-b border-slate-100 hover:bg-slate-50 cursor-pointer transition-colors ${isExpanded ? 'bg-slate-50' : ''}`}
                      >
                        <td className="p-4 font-bold text-slate-400">#{c.no}</td>
                        <td className="p-4 font-black text-slate-800">{c.constituency}</td>
                        <td className="p-4 font-bold text-slate-500">{c.district}</td>
                        <td className="p-4 font-bold text-slate-700 text-right">{c.total}</td>
                        <td className="p-4 font-black text-[#FF3B30] text-right">{c.pending}</td>
                        <td className="p-4 font-bold text-emerald-600 text-right">{c.resolved}</td>
                        <td className="p-4 font-black text-slate-700 text-right">
                          <div className="flex items-center justify-end gap-2">
                            <span>{c.rate}%</span>
                            <div className="w-8 h-1.5 bg-slate-200 rounded-full overflow-hidden">
                              <div className="h-full bg-emerald-500" style={{ width: `${c.rate}%` }}></div>
                            </div>
                          </div>
                        </td>
                        <td className="p-4 text-slate-400 text-right">
                          {isExpanded ? <ChevronUp className="w-4 h-4 inline" /> : <ChevronDown className="w-4 h-4 inline" />}
                        </td>
                      </tr>
                      <AnimatePresence>
                        {isExpanded && (
                          <motion.tr 
                            initial={{ opacity: 0, height: 0 }} 
                            animate={{ opacity: 1, height: 'auto' }} 
                            exit={{ opacity: 0, height: 0 }}
                          >
                            <td colSpan={8} className="bg-slate-50 border-b border-slate-200 p-0">
                              <div className="p-6">
                                <h4 className="text-[10px] font-black text-slate-500 uppercase tracking-widest mb-3 border-b border-slate-200 pb-2">
                                  Departmental Breakdown: {c.constituency}
                                </h4>
                                {deptBreakdown.length > 0 ? (
                                  <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-3">
                                    {deptBreakdown.map(db => (
                                      <div key={db.dept} className="bg-white border border-slate-200 rounded-xl p-3 shadow-sm flex flex-col justify-between">
                                        <span className="font-bold text-slate-800 text-[11px] truncate mb-2" title={db.dept}>{db.dept}</span>
                                        <div className="flex justify-between items-end">
                                          <div className="text-left">
                                            <span className="block text-[8px] font-bold text-emerald-500 uppercase">Resolved</span>
                                            <span className="font-bold text-slate-700">{db.resolved}</span>
                                          </div>
                                          <div className="text-right">
                                            <span className="block text-[8px] font-bold text-orange-500 uppercase">Pending</span>
                                            <span className="font-black text-[#FF3B30]">{db.pending}</span>
                                          </div>
                                        </div>
                                      </div>
                                    ))}
                                  </div>
                                ) : (
                                  <div className="text-slate-400 font-bold text-xs py-2">No grievances reported for this constituency.</div>
                                )}
                              </div>
                            </td>
                          </motion.tr>
                        )}
                      </AnimatePresence>
                    </React.Fragment>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    );
  };

  const renderCabinetReport = () => {
    return (
      <div className="max-w-3xl mx-auto space-y-6">
        <div className="bg-white rounded-3xl p-8 shadow-sm border border-slate-200 text-center">
          <div className="w-16 h-16 bg-red-50 rounded-full flex items-center justify-center mx-auto mb-4 border border-red-200">
            <List className="w-8 h-8 text-[#FF3B30]" />
          </div>
          <h2 className="text-xl font-black text-slate-800 uppercase tracking-wide mb-2">Automate Cabinet Performance Summary</h2>
          <p className="text-slate-500 font-bold text-xs max-w-md mx-auto mb-6">
            Compiles resolution rates, pending volumes, and efficiency rankings across all ministerial departments based on macro-level state data.
          </p>
          <button 
            onClick={handleGenerateCabinetReport}
            className="bg-[#FF3B30] hover:bg-red-650 text-white px-8 py-3.5 rounded-xl font-black uppercase tracking-wider text-xs shadow-md transition-colors flex items-center justify-center gap-1.5 mx-auto"
          >
            <Download className="w-4 h-4" /> Run Cabinet Audit Report
          </button>

          {cabinetReport && (
            <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="mt-8 text-left space-y-4">
              <div className="bg-emerald-50 text-emerald-700 px-4 py-3 rounded-lg font-bold text-xs mb-4 flex items-center gap-2 justify-center border border-emerald-200">
                ✓ Cabinet audit generated successfully.
              </div>

              <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200 text-xs font-mono text-slate-700 whitespace-pre-wrap shadow-inner overflow-auto max-h-96">
{`JANANAYAGAM — CABINET REPORT
Tamil Nadu Civic Command Center
Generated: ${cabinetReport.date}
========================================

STATE CABINET RANKINGS (By Efficiency & Resolution Rate)

${cabinetReport.rankings.map((rank, idx) => `${idx + 1}. Department of ${rank.dept}
   - Minister-in-Charge: ${rank.minister}
   - Resolution Rate: ${rank.rate}%
   - Unresolved Backlog: ${rank.pending}`).join('\n\n')}

SUMMARY FINDINGS:
${cabinetReport.summaryText}

========================================
Confidential — Office of the Chief Minister`}
              </div>
            </motion.div>
          )}
        </div>
      </div>
    );
  };

  const renderAnnouncements = () => (
    <div className="max-w-2xl mx-auto bg-white rounded-3xl p-6 shadow-sm border border-slate-200/80 space-y-6">
      <div className="border-b border-slate-100 pb-4">
        <h3 className="font-black text-slate-800 text-sm uppercase tracking-wide flex items-center gap-2">
          <Megaphone className="w-5 h-5 text-[#FF3B30]" /> CM Broadcast announcement Console
        </h3>
        <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mt-0.5 block">
          Dispatch statewide news feeds to citizens
        </span>
      </div>

      <form onSubmit={handleBroadcast} className="space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-slate-555 uppercase tracking-widest pl-0.5 block">Announcement Title</label>
            <input
              type="text" required placeholder="Headline..."
              value={broadcastTitle} onChange={e => setBroadcastTitle(e.target.value)}
              className="w-full bg-slate-50 border border-slate-200 text-xs font-bold rounded-xl outline-none p-2.5 focus:border-[#FF3B30]"
            />
          </div>
          <div className="space-y-1">
            <label className="text-[10px] font-bold text-slate-555 uppercase tracking-widest pl-0.5 block">Target Scope</label>
            <select
              value={broadcastDistrict}
              onChange={e => setBroadcastDistrict(e.target.value)}
              className="w-full bg-slate-50 border border-slate-200 text-xs font-bold rounded-xl p-2.5 outline-none cursor-pointer"
            >
              <option value="All">Statewide (All Citizens)</option>
              {[...new Set(tickets.map(t => t.district))].filter(Boolean).map(d => <option key={d} value={d}>{d}</option>)}
            </select>
          </div>
        </div>

        <div className="space-y-1">
          <label className="text-[10px] font-bold text-slate-555 uppercase tracking-widest pl-0.5 block font-sans">Announcement Body</label>
          <textarea
            rows={5} required
            value={broadcastText} onChange={e => setBroadcastText(e.target.value)}
            placeholder="Type statement contents..."
            className="w-full bg-slate-50 border border-slate-200 text-xs font-bold rounded-xl outline-none p-3.5 focus:border-[#FF3B30] resize-none leading-relaxed"
          ></textarea>
        </div>

        <button 
          type="submit"
          className="w-full bg-[#FF3B30] hover:bg-red-650 text-white py-3.5 rounded-xl text-[10px] font-black uppercase tracking-wider transition-colors shadow-md flex items-center justify-center gap-1.5"
        >
          <Send className="w-4 h-4" /> Broadcast Announcement
        </button>
      </form>
    </div>
  );

  return (
    <div className="flex h-screen bg-[#F0EBE3] font-sans">
      {renderSidebar()}
      
      <main className="flex-1 overflow-y-auto relative flex flex-col">
        {/* Header Ribbon */}
        <div className="bg-[#1E1E1E] text-white p-6 shadow-md flex justify-between items-center z-10 relative overflow-hidden shrink-0 border-b border-slate-800">
          <div className="absolute top-0 right-0 -mt-6 -mr-6 w-24 h-24 bg-white/5 rounded-full blur-xl"></div>
          <div>
            <h1 className="text-xl font-black uppercase tracking-wider flex items-center gap-2">
              <Shield className="w-5 h-5 text-[#FF3B30]" /> MACRO GOVERNANCE COMMAND
            </h1>
            <span className="text-[9px] text-[#FF3B30] font-extrabold uppercase tracking-widest bg-[#FF3B30]/10 border border-[#FF3B30]/20 px-2 py-0.5 rounded mt-1.5 inline-block">
              Statewide Civic Grid
            </span>
          </div>
          <div className="text-right bg-slate-900 border border-slate-800 p-2.5 rounded-xl">
            <span className="text-[8px] font-bold text-slate-500 uppercase tracking-widest block">GIS Clock Lock</span>
            <span className="font-mono text-xs font-black text-[#FF3B30]">{new Date().toLocaleTimeString()}</span>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto p-4 md:p-8">
          <AnimatePresence mode="wait">
            <motion.div
              key={activeMenu}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.2 }}
              className="h-full"
            >
              {activeMenu === 'dashboard' && renderDashboard()}
              {activeMenu === 'constituencies' && renderConstituenciesTab()}
              {activeMenu === 'cabinet' && renderCabinetReport()}
              {activeMenu === 'broadcast' && renderAnnouncements()}
            </motion.div>
          </AnimatePresence>
        </div>
      </main>
    </div>
  );
}
